name: ComptaLibre CI (Validation)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-on-version: "20"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Vérification du code
        run: npm run lint

      - name: Test du Build de production
        run: npm run build
